version: 2
updates:
  - package-ecosystem: "gradle" # Specify Gradle as the ecosystem
    directory: "/" # Root directory where your Gradle files are located
    schedule:
      interval: "weekly" # Check for updates every week
    open-pull-requests-limit: 5 # Limits the number of open PRs
